#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 23 15:48:42 2026

@author: vahid
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.io import wavfile


def plot_wav_borders(tsv_path, wav_path, save_plot=False, output_path=None, show_plot=True):
    """
    Plot a WAV waveform together with onset and offset borders from a TSV file.
    The TSV file must contain at least these columns. you can simply give the TSV file that generated by inference code:
        wav_file
        onset_sec
        offset_sec

    Parameters
    tsv_path : str
        Path to the TSV file containing the onset/offset information.

    wav_path : str
        Path to the WAV file that should be plotted.

    save_plot : bool, optional
        If True, save the generated plot.
        Default is False.

    output_path : str or None, optional
        Path where the plot should be saved.

        Example:
            "./plots/trial_01.png"

        If save_plot=True and output_path=None, the plot will be saved
        beside the WAV file.

    show_plot : bool, optional
        If True, display the plot.
        Default is True.

    Returns
    -------
    fig, Matplotlib figure and axis objects.
    """

    # ---------------------------------------------------------
    # Read TSV file
    df = pd.read_csv(tsv_path, sep="\t")
    required_columns = ["wav_file", "onset_sec", "offset_sec"]
    for column in required_columns:
        if column not in df.columns:
            raise ValueError(f"Required column '{column}' was not found in the TSV file.")

    # ---------------------------------------------------------
    # Get WAV file name
    wav_name = os.path.basename(wav_path)
    # Find only the rows belonging to this WAV file
    wav_rows = df[df["wav_file"] == wav_name].copy()
    if wav_rows.empty:
        raise ValueError(f"No rows were found in the TSV file for:\n{wav_name}")
    # Sort borders if syllable_number exists
    if "syllable_number" in wav_rows.columns:
        wav_rows = wav_rows.sort_values("syllable_number")

    # ---------------------------------------------------------
    # Read WAV file
    sample_rate, audio = wavfile.read(wav_path)
    # If stereo, convert to mono
    if audio.ndim == 2:
        audio = audio.mean(axis=1)
    # Create time axis in seconds
    time = np.arange(len(audio)) / sample_rate

    # ---------------------------------------------------------
    # Get onset and offset borders
    onset_times = wav_rows["onset_sec"].dropna().astype(float).to_numpy()
    offset_times = wav_rows["offset_sec"].dropna().astype(float).to_numpy()
    # ---------------------------------------------------------
    # Plot waveform
    fig, ax = plt.subplots(figsize=(16, 5))
    ax.plot(time, audio, linewidth=0.8, color="blue", label="Waveform")

    # ---------------------------------------------------------
    # Plot onset borders
    for i, onset in enumerate(onset_times):
        ax.axvline(x=onset, color="green", linestyle="--", linewidth=3, alpha=0.9, label="Onset" if i == 0 else None)
    # ---------------------------------------------------------
    # Plot offset borders
    for i, offset in enumerate(offset_times):
        ax.axvline(x=offset, color="red", linestyle="--", linewidth=2.0, alpha=0.8, label="Offset" if i == 0 else None)

    # ---------------------------------------------------------
    # Plot formatting
    ax.set_title(wav_name, fontsize=14)
    ax.set_xlabel("Time (seconds)")
    ax.set_ylabel("Amplitude")
    ax.set_xlim(0, time[-1])
    ax.legend()
    ax.grid(True, alpha=0.2)
    plt.tight_layout()

    # ---------------------------------------------------------
    # Save plot if requested
    if save_plot:
        if output_path is None:
            wav_folder = os.path.dirname(wav_path)
            wav_without_extension = os.path.splitext(wav_name)[0]
            output_path = os.path.join(
                wav_folder,
                wav_without_extension + "_borders.png")
        # Create output directory if necessary
        output_directory = os.path.dirname(output_path)
        if output_directory:
            os.makedirs(output_directory, exist_ok=True)
        fig.savefig(output_path, dpi=300, bbox_inches="tight")
        print(f"Plot saved to: {output_path}")

    # ---------------------------------------------------------
    # Show plot
    if show_plot:
        plt.show()
    else:
        plt.close(fig)
    return fig, ax


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# here is an example of how to use the function to plot the predicted borders on a single wave file
"""
# Please use the function like this:
plot_wav_borders(tsv_path="/Users/vahid/Desktop/for_Sivan/Amanda_data/Output_TSV/sub_01.tsv",
                 wav_path="/Users/vahid/Desktop/for_Sivan/Amanda_data/formatted_data/sub-01/behav_sub-01_run-01_trial-01.wav",
                 save_plot=True,
                 output_path="/Users/vahid/Desktop/for_Sivan/Amanda_data/formatted_data/plots/sub01/behav_sub-01_run-01_trial-01.png")
"""



#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Here is an example of how to use the fuction to ploting the predicted borders on multiple images in sub-plot.
# Here by default I determined to have 5 sub-plot. So, it can plot 5 different wave files.
# 


'''
import os
import glob
import matplotlib.pyplot as plt

# Paths
tsv_path = "/Users/vahid/Desktop/for_Sivan/Amanda_data/Output_TSV/sub_01.tsv"
wav_folder = "/Users/vahid/Desktop/for_Sivan/Amanda_data/formatted_data/sub-01"
output_folder = "/Users/vahid/Desktop/for_Sivan/Amanda_data/formatted_data/plots/sub01"

# Automatically find all WAV files in the folder
wav_files = sorted(glob.glob(os.path.join(wav_folder, "*.wav")))
print(f"Found {len(wav_files)} WAV files.")

# Plot 5 WAV files in each figure
plots_per_figure = 5

for start_index in range(0, len(wav_files), plots_per_figure):
    # Get the next 5 WAV files
    current_wav_files = wav_files[start_index:start_index + plots_per_figure]
    number_of_plots = len(current_wav_files)
    # Create subplots
    fig, axes = plt.subplots(number_of_plots,1,figsize=(16, 4 * number_of_plots))
    # If only one subplot exists
    if number_of_plots == 1:
        axes = [axes]
    
    # Process each WAV using your existing function
    for new_ax, wav_path in zip(axes, current_wav_files):
        # Call your existing function
        temp_fig, temp_ax = plot_wav_borders(tsv_path=tsv_path, wav_path=wav_path,
            save_plot=False, show_plot=False)

        # Copy all lines to the new subplot
        for line in temp_ax.get_lines():
            new_ax.plot(line.get_xdata(), line.get_ydata(),
                color=line.get_color(), linestyle=line.get_linestyle(),
                linewidth=line.get_linewidth(), alpha=line.get_alpha(),
                label=line.get_label())

        # Copy title and limits
        new_ax.set_title(temp_ax.get_title())
        new_ax.set_xlabel("Time (seconds)")
        new_ax.set_ylabel("Amplitude")
        new_ax.set_xlim(temp_ax.get_xlim())
        new_ax.grid(True, alpha=0.2)
        new_ax.legend()

        # Close temporary figure
        plt.close(temp_fig)
    # Final formatting
    plt.tight_layout()

    # Save this group of 5
    os.makedirs(output_folder, exist_ok=True) 
    figure_number = start_index // plots_per_figure + 1

    output_path = os.path.join(output_folder,
        f"border_plots_{figure_number}.png")

    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    print(f"Saved: {output_path}")
    plt.show()


'''




